name: Build resources & Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Compile Qt resources (using PyQt pyrcc_main)
        run: |
          # Use the PyQt5 provided pyrcc_main module so compilation works after `pip install PyQt5`
          python -m PyQt5.pyrcc_main -o gui/resources/rc_icons.py gui/resources/icons.qrc || true
          python -m PyQt5.pyrcc_main -o gui/resources/rc_skill_icons.py gui/resources/skill_icons.qrc || true

      - name: Ensure compiled resources are up-to-date
        run: |
          # fail if compiled resource files changed (meaning they need to be committed)
          git config --global user.email action@github.com
          git config --global user.name "GitHub Action"
          git add -A
          if ! git diff --quiet -- gui/resources/rc_icons.py gui/resources/rc_skill_icons.py; then
            echo "Compiled resource files are out-of-date. Please run the resource build locally and commit rc_icons.py / rc_skill_icons.py.";
            git --no-pager diff -- gui/resources/rc_icons.py gui/resources/rc_skill_icons.py || true;
            exit 1;
          fi

      - name: Run tests
        run: |
          python -m pytest -q
